import json
import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[1]


class FrontendContractTests(unittest.TestCase):
    def test_react_workbench_declares_ant_design_stack(self):
        package = json.loads((ROOT / "frontend" / "package.json").read_text(encoding="utf-8"))
        dependencies = {**package["dependencies"], **package["devDependencies"]}
        for name in ("react", "react-dom", "antd", "@ant-design/x", "vite"):
            self.assertIn(name, dependencies)

    def test_workbench_uses_thought_chain_and_existing_api_routes(self):
        source = (ROOT / "frontend" / "src" / "main.jsx").read_text(encoding="utf-8")
        # The workbench keeps @ant-design/x as a supported dependency, but the
        # visible chain is rendered directly so its icon/toggle hit areas stay
        # stable across Ant Design X releases.
        self.assertIn("function ThoughtEvent", source)
        self.assertIn('className={`thought-icon thought-icon-${kind}`}', source)
        self.assertIn('MISSION ? "点击开始任务，或者描述一个任务"', source)
        self.assertNotIn('MISSION ? "你可以直接点击开始任务', source)
        self.assertIn('<RecursiveInfo value={missionContext} />', source)
        self.assertIn('MissionInfo open={missionInfoOpen}', source)
        self.assertIn('normalizeEvents(current)', source)
        self.assertIn('autoApproveRef.current', source)
        self.assertIn('approve(event.id, true, task)', source)
        self.assertIn('approvalInFlightRef', source)
        self.assertIn('approve(pending.id, true, current)', source)
        self.assertIn('event.type === "thinking" ? <ThinkingIcon />', source)
        self.assertIn('return source.reduce((events, event) =>', source)
        self.assertIn('events[events.length - 1] = { ...last, text:', source)
        self.assertIn('const waitingForNextEvent = busy && !["done", "error", "approval_request"].includes(lastEvent?.type);', source)
        self.assertIn('event={{ type: "thinking", text: "" }}', source)
        self.assertIn('const approved = event.type === "approval_request" && approvalResult?.approved === true;', source)
        self.assertIn('✓ 已允许执行', source)
        self.assertIn('const approvalResults = events.reduce((result, event) =>', source)
        self.assertIn('event.type === "approval_result" ? "approval-result"', source)
        self.assertIn('event.type === "approval_result" && event.approved ? "✓"', source)
        self.assertIn('event.type === "approval_request" ? "?"', source)
        self.assertIn('function ModelSettingsIcon()', source)
        self.assertIn('<ModelSettingsIcon /> 大语言模型设置', source)
        self.assertIn('function HistoryIcon()', source)
        self.assertIn('<HistoryIcon />历史会话', source)
        self.assertIn('>+ 新会话</Button>', source)
        self.assertIn('M15.167 8c0 .99', source)
        self.assertIn('modelText.length > 15 ? `${modelText.slice(0, 15)}...` : modelText', source)
        self.assertNotIn('DownOutlined', source)
        self.assertIn('function SendArrowIcon()', source)
        self.assertIn('fill="#fff"', source)
        self.assertIn(': <SendArrowIcon />', source)
        self.assertIn('function CurrentMissionIcon()', source)
        self.assertIn('function UploadFileIcon()', source)
        self.assertIn('<CurrentMissionIcon /> 当前任务信息', source)
        self.assertIn('<UploadFileIcon /> <span>上传文件</span>', source)
        upload_icon_start = source.index('function UploadFileIcon()')
        upload_icon_end = source.index('function DownloadSelectedIcon()')
        self.assertIn('fill="currentColor"', source[upload_icon_start:upload_icon_end])
        self.assertIn('function DownloadSelectedIcon()', source)
        self.assertIn('fillRule="evenodd"', source)
        self.assertIn('icon={<DownloadSelectedIcon />}', source)
        self.assertIn('function ReadFileIcon()', source)
        self.assertIn('function WriteFileIcon()', source)
        self.assertIn('function UploadMinioIcon()', source)
        upload_minio_start = source.index('function UploadMinioIcon()')
        upload_minio_end = source.index('function AuditIcon()')
        self.assertIn('fill="currentColor"', source[upload_minio_start:upload_minio_end])
        self.assertIn('function TaskEditIcon()', source)
        self.assertIn('function TaskCompleteIcon()', source)
        complete_icon_start = source.index('function TaskCompleteIcon()')
        complete_icon_end = source.index('function TaskFilesIcon()')
        self.assertIn('fill="#fff"', source[complete_icon_start:complete_icon_end])
        self.assertIn('function TaskFilesIcon()', source)
        self.assertIn('function FolderPanelIcon()', source)
        self.assertIn('function FileGroupChevronIcon({ collapsed })', source)
        self.assertIn('<FileGroupChevronIcon collapsed={collapsed} />', source)
        self.assertIn('icon={active?.platformStatus === "COMPLETED" ? <TaskEditIcon /> : <TaskCompleteIcon />}', source)
        self.assertIn('icon={<TaskFilesIcon />}', source)
        self.assertIn('<FolderPanelIcon />', source)
        self.assertIn('function AuditIcon()', source)
        self.assertIn('M9.75 10V7.437', source)
        self.assertIn('function TaskUpdateIcon()', source)
        self.assertIn('function CommandIcon()', source)
        self.assertIn('function ThinkingIcon()', source)
        thinking_icon_start = source.index('function ThinkingIcon()')
        thinking_icon_end = source.index('function CommandIcon()')
        self.assertIn('viewBox="0 0 16 16"', source[thinking_icon_start:thinking_icon_end])
        self.assertIn('fill="currentColor"', source[thinking_icon_start:thinking_icon_end])
        command_icon_start = source.index('function CommandIcon()')
        command_icon_end = source.index('function isExpiredApprovalError(error)')
        self.assertIn('viewBox="0 0 48 48"', source[command_icon_start:command_icon_end])
        self.assertIn('stroke="currentColor"', source[command_icon_start:command_icon_end])
        self.assertIn('event.type === "thinking" ? <ThinkingIcon />', source)
        self.assertNotIn('event.type === "thinking" ? "·"', source)
        model_icon_start = source.index('function ModelSettingsIcon()')
        model_icon_end = source.index('function TaskUpdateIcon()')
        self.assertIn('fill="currentColor"', source[model_icon_start:model_icon_end])
        self.assertIn('fill="#fff"', source)
        self.assertIn('isReadTool ? <ReadFileIcon />', source)
        self.assertIn('isWriteTool || isEditTool ? <WriteFileIcon />', source)
        self.assertIn('isAudit ? <AuditIcon />', source)
        self.assertIn('isTaskUpdate ? <TaskUpdateIcon />', source)
        self.assertIn('isCommand ? <CommandIcon />', source)
        self.assertIn('icon={<UploadMinioIcon />}', source)
        self.assertIn('event.type === "error" || event.is_error ? "!"', source)
        self.assertIn('const executionFinished = event.type === "approval_request" && events.slice(index + 1).some((candidate) => candidate.type === "done");', source)
        self.assertIn('event.type === "approval_request" && !completed', source)
        self.assertIn('className: "thought-collapsed-row thought-collapsed-row-clickable"', source)
        self.assertIn('const collapsedRowProps = {', source)
        self.assertIn('role: "button"', source)
        self.assertIn('clickEvent.stopPropagation(); onFile(part);', source)
        self.assertIn('const feedRef = useRef(null);', source)
        self.assertIn('const feedPinnedRef = useRef(true);', source)
        self.assertIn('if (MISSION) await loadMission();', source)
        self.assertIn('await loadTasks();', source)
        self.assertIn('if (feed && feedPinnedRef.current) feed.scrollTop = feed.scrollHeight;', source)
        self.assertIn('feedPinnedRef.current = feed.scrollHeight - feed.scrollTop - feed.clientHeight <= 56;', source)
        self.assertIn('onScroll={handleFeedScroll}', source)
        self.assertIn('feed.scrollTop = feed.scrollHeight;', source)
        self.assertIn('}, [events, busy, view]);', source)
        self.assertIn('<div ref={feedRef} className="feed" onScroll={handleFeedScroll}>', source)
        self.assertIn('body: JSON.stringify({ message: content, displayMessage, startTask, intent })', source)
        self.assertNotIn('startTask, missionContext:', source)
        self.assertIn('function missionIdentity(task = null)', source)
        self.assertIn('const taskMission = missionIdentity(task)', source)
        self.assertIn('sendToTask(task, messageText, display, start, intent)', source)
        self.assertIn('function formatDuration(durationMs)', source)
        self.assertIn('`已思考 ${formatDuration(durationMs)}`', source)
        self.assertIn('durationMs={eventDuration(events, index)}', source)
        self.assertIn('["done", "tool_result", "approval_result", "audit", "error"]', source)
        self.assertIn('event = stampEvent(event);', source)
        styles = (ROOT / "frontend" / "src" / "styles.css").read_text(encoding="utf-8")
        self.assertIn('.thought-icon-approval-result{color:#7c3aed;background:#ede9fe}', styles)
        self.assertIn('.chain-event-approval-result .thought-toggle{color:#7c3aed}', styles)
        self.assertIn('.thought-summary{flex:1;min-width:0;max-width:100%', styles)
        self.assertIn('.thought-duration{flex:none;', styles)
        self.assertIn('.thought-collapsed-row-clickable{display:flex;width:75%;max-width:75%', styles)
        self.assertIn('.thought-collapsed-row-clickable:hover{background:#f1f5f9;box-shadow:0 2px 8px rgba(15,23,42,.14)}', styles)
        self.assertIn('.chain-event{position:relative;padding:3px 0;', styles)
        self.assertIn('.feed-list{gap:2.4px}', styles)
        self.assertIn('.chain-event::before{display:none!important;content:none!important}.chain-event:not(:last-child)::after{left:17px;top:27px;bottom:-7px;width:1px;background:#cbd5e1}', styles)
        self.assertIn('.thought-icon-error{color:#b91c1c;background:#fee2e2}', styles)
        self.assertIn('.approval-actions .ant-btn-primary,.file-actions .ant-btn-primary{background:#2563eb!important', styles)
        self.assertIn('.new-task,.start-button,.send-button{background:linear-gradient(135deg,#2563eb,#1e40af)!important', styles)
        self.assertIn('.new-task{height:32px!important;margin:10px 0 0', styles)
        self.assertIn('.approval-actions .ant-btn-primary:disabled,.auto-approve-toggle,.file-actions .ant-btn-primary{font-weight:400!important}', styles)
        self.assertIn('.approval-actions .ant-btn-primary:disabled,.file-actions .ant-btn-primary,.auto-approve-toggle.ant-btn-primary{background:#fff!important', styles)
        self.assertIn('.auto-approve-toggle.ant-btn-default{background:#fff!important;border-color:#d9d9d9!important', styles)
        self.assertIn('.task-header .ant-btn-primary{background:linear-gradient(135deg,#2563eb,#1e40af)!important', styles)
        self.assertIn('.auto-approve-toggle.ant-btn-default{background:#fff!important;border-color:#d9d9d9!important', styles)
        self.assertIn('.file-row>input[type=checkbox]{margin-left:19px', styles)
        self.assertIn('.thought-icon-read-file{color:#0f766e;background:#ccfbf1}', styles)
        self.assertIn('.thought-icon-write-file,.thought-icon-edit-file{color:#c2410c;background:#ffedd5}', styles)
        self.assertIn('.thought-icon-read-file svg,.thought-icon-write-file svg,.thought-icon-edit-file svg,.thought-icon-audit svg,.thought-icon-task-update svg,.thought-icon-command svg{width:12px;height:12px}', styles)
        self.assertIn('.thought-icon-audit{color:#8f9299;background:#f1f5f9}', styles)
        self.assertIn('.model-settings-icon{display:block;flex:none;width:16px;height:16px}', styles)
        self.assertIn('.thought-icon-task-update{color:#7c3aed;background:#ede9fe}', styles)
        self.assertIn('.thought-icon-command{color:#2563eb;background:#dbeafe}', styles)
        self.assertIn('.thought-icon-thinking svg{width:12px;height:12px}', styles)
        self.assertIn('上传到 MinIO', source)
        self.assertIn('const uploadToMinio = async () =>', source)
        self.assertNotIn('prefix: missionContext?.outputPrefix', source)
        self.assertIn('const intent = start ? "execute" : task.platformStatus === "COMPLETED" ? "chat" : "auto";', source)
        self.assertIn('onUploadToMinio={uploadToMinio}', source)
        self.assertIn('["mission-input", "mission-output", "mission-work"].forEach', source)
        self.assertIn('return ["mission-input", "mission-output", "mission-work"].includes(first) ? first : ""', source)
        self.assertIn('const defaultCollapsedDirs = () => new Set(["", "mission-input", "mission-work"]);', source)
        self.assertIn('setCollapsedDirs(defaultCollapsedDirs());', source)
        self.assertIn('!files.length && !mission ? <Empty description="暂无文件" />', source)
        self.assertIn('className="file-group-empty">暂无文件', source)
        self.assertIn('modelingPlan: "分层建模计划"', source)
        self.assertIn('artifactType: "Artifact 类型"', source)
        self.assertIn('if (result.completionHint) messageApi.info(result.completionHint);', source)
        self.assertIn('const changePlatformStatus = async () =>', source)
        self.assertIn('/api/tasks/${active.id}/platform-status', source)
        self.assertIn('isMissionTask && active?.platformStatus !== "FAILED" && <Button type={active?.platformStatus === "COMPLETED" ? "default" : "primary"}', source)
        self.assertIn('mission={isMissionTask}', source)
        self.assertIn('const toggleAutoApprove = () =>', source)
        self.assertIn('已开启自动确认', source)
        self.assertIn('已关闭自动确认', source)
        self.assertIn('showAutoApprove={isMissionTask}', source)
        self.assertIn('上传文件</span></Button>', source)
        self.assertIn('上传新结果将恢复任务为执行中', source)
        self.assertIn('<Button className="new-task" onClick={handleNewSession}>+ 新会话</Button>', source)
        self.assertIn('const reuseMissionTask = async () =>', source)
        self.assertIn('const handleNewSession = async () =>', source)
        self.assertIn('if (MISSION) {\n      await reuseMissionTask();\n      return;', source)
        self.assertIn('messageApi.success("已复用当前任务，不会新建会话")', source)
        self.assertNotIn('import * as XLSX from "xlsx";', source)
        self.assertIn('import("xlsx")', source)
        self.assertIn('URL.revokeObjectURL(previewImageUrlRef.current)', source)
        self.assertIn('requestId !== previewRequestRef.current', source)
        self.assertIn('uploadBlocked={busy || active?.status === "working" || platformActionLoading}', source)
        self.assertIn('任务已完成，请先点击“修改”再上传新的输入文件', source)
        self.assertIn('const refreshedTasks = await loadTasks();', source)
        self.assertIn('function isExpiredApprovalError(error)', source)
        self.assertIn('if (!isExpiredApprovalError(result.error)) messageApi.error(result.error);', source)
        self.assertNotIn('else messageApi.warning(result.error);', source)
        for route in ("/api/tasks", "/api/files", "/api/mission/task", "/api/tasks/${task.id}/send", "/api/minio/upload"):
            self.assertIn(route, source)

    def test_python_server_prefers_built_frontend_with_safe_assets(self):
        source = (ROOT / "open-claude" / "oc_codex_server.py").read_text(encoding="utf-8")
        self.assertIn("FRONTEND_DIST", source)
        self.assertIn("_serve_frontend_asset", source)
        self.assertIn('"..", "frontend", "dist"', source)
        self.assertIn('html_path = os.path.join(FRONTEND_DIST, "index.html")', source)
        self.assertIn("built React frontend not found; run npm run build", source)
        self.assertNotIn("HTML_PATH", source)
        self.assertNotIn("codex_web.html", source)
        self.assertIn('cache_control="public, max-age=31536000, immutable"', source)
        self.assertIn("def _stamp_event(event)", source)
        self.assertIn('"timestamp": time.time()', source)
        self.assertIn('thinking_event = self._record_event({"type": "thinking", "text": ev["text"]})', source)
        self.assertIn('emit(thinking_event)', source)

    def test_legacy_static_frontends_are_removed(self):
        self.assertEqual([], sorted(ROOT.glob("*.html")))
        for name in ("codex_web.html", "generic_claude_gpt_style_chat.html"):
            self.assertFalse((ROOT / "open-claude" / name).exists())


if __name__ == "__main__":
    unittest.main()
